FROM ubuntu:16.04

RUN apt-get update && apt-get install --no-install-recommends -y mercurial libexpat1-dev git-core build-essential bison \
    flex libssl-dev libdb-dev libpcap-dev libc6-dbg libsysfs-dev gawk indent \
    pkg-config autoconf automake sudo ccache libsaxonb-java openjdk-8-jre-headless \
    bc wget && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash ns3dce && adduser ns3dce sudo && echo -n 'ns3dce:ns3dce' | chpasswd

# Enable passwordless sudo for users under the "sudo" group
RUN sed -i.bkp -e \
      's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' \
      /etc/sudoers

USER ns3dce
WORKDIR /home/ns3dce/

ENV PATH /usr/lib/ccache:${PATH}

# bake
RUN mkdir -p /home/ns3dce/dce-linux-dev
WORKDIR /home/ns3dce/dce-linux-dev
RUN git clone https://github.com/thehajime/bake

WORKDIR /home/ns3dce/dce-linux-dev/bake
COPY bakeconf.xml.patch .
RUN git apply < bakeconf.xml.patch

WORKDIR /home/ns3dce/dce-linux-dev

RUN ./bake/bake.py configure -e dce-linux-dev -e iperf && \
    ./bake/bake.py download

WORKDIR /home/ns3dce/dce-linux-dev/source/ns-3-dev
RUN git config --global user.email "ns3dce@localhost"
RUN git config --global user.name "ns-3 DCE"
RUN git revert 94de5084e7430bb51c8176cd99703e552e305391

WORKDIR /home/ns3dce/dce-linux-dev/source/ns-3-dev
COPY ns3.patch .
RUN git apply < ns3.patch

WORKDIR /home/ns3dce/dce-linux-dev
RUN ./bake/bake.py build -j $(nproc)

RUN cd source/dce-linux-dev && python3 ./test.py -v -c unit
